[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer', 'php82Extensions.pdo_mysql', 'php82Extensions.mysqli']

[phases.install]
cmds = [
    'composer install --no-dev --optimize-autoloader --no-interaction'
]

[phases.build]
cmds = [
    'mkdir -p storage/logs storage/framework/cache storage/framework/sessions storage/framework/views',
    'chmod -R 775 storage',
    'chmod -R 775 bootstrap/cache'
]

[start]
cmd = './start.sh'
