[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer', 'php82Extensions.pdo', 'php82Extensions.pdo_pgsql', 'php82Extensions.pgsql', 'postgresql', 'postgresql_15']

[phases.install]
cmds = [
    'composer install --no-dev --optimize-autoloader --no-interaction'
]

[phases.build]
cmds = [
    'mkdir -p storage/logs storage/framework/cache storage/framework/sessions storage/framework/views',
    'chmod -R 775 storage',
    'chmod -R 775 bootstrap/cache',
    'php -m | grep -i pdo || echo "PDO extensions check failed"',
    'php -m | grep -i pgsql || echo "PostgreSQL extensions check failed"',
    'php -r "echo \"Available PDO drivers: \" . implode(\", \", PDO::getAvailableDrivers()) . PHP_EOL;"'
]

[start]
cmd = './start.sh'
